### ISSUE TITLE
Test pretty printing

### ISSUE THREAD

**Issue by mmhat** [knrafto/language-bash#27]
While working on #24 it turned out that the current test suite performed poorly.
Proposal:

1. Drop a bash snippet somewhere in the tests/ directory
2. Discover those snippets
3. Parse them
4. Pretty print them
5. Compare the output to a golden file using [tasty-golden](https://hackage.haskell.org/package/tasty-golden)
6. Run bash on the original file and the pretty printed one and compare the output

This is of course only for those tests involving pretty printing; we can keep the existing unit tests as they are.
Additionally we could fuzzy test the implementation with QuickCheck.

**Comment by knrafto** [comment]
Sounds great! Could we scope the issue down to "test pretty-printing" and open new issues for other possible improvements? Otherwise we'd never be able to close this issue - the test suite could always be improved :)

Possibly dumb question, why is TemplateHaskell required for step 2 instead of discovering the files at runtime?

**Comment by mmhat** [comment]
Your right, I changed the title and 2. of the issue.
